### ISSUE TITLE
Supported Cypher Syntax

### ISSUE THREAD

**Issue by Uria1** [apache/incubator-age#102]
Is there a list of supported & unsupported Cypher syntax?
I tried using `MERGE` and `OPTIONAL MATCH` and I get a syntax error for both.

**Comment by aked21** [comment]
@jrgemignani @JoshInnis 
Guys, please assist @Uria1 on this?

**Comment by emotionbug** [comment]
@Uria1 
currently, not supporting `MERGE` and `OPTIONAL MATCH` clause.
as i know, currently supports `CREATE`, `MATCH`, `DELETE`, `SET`, `REMOVE`, `CASE` clause are working.

except, VLE ( in neo4j called `Variable-length pattern matching` ) feature.

follow the roadmap, on the next release will be supports VLE and `MERGE` clause.

**Comment by Uria1** [comment]
thanks!
regarding the optional match... what I'm trying to do is find out if certain nodes exist.
i.e.
```
MATCH (a:country {name:'Italy'})
MATCH (b:country {name:'France'})
return a,b
```
In case both nodes exist, I get both returned which is fine. However, if only one node exist I get nothing back.
Is there a way around it?

**Comment by audiBookning** [comment]
> In case both nodes exist, I get both returned which is fine. However, if only one node exist I get nothing back.
> Is there a way around it?

I haven't tried it but, at first sight for that case, i personally would try the `WITH` clause to separate the two `MATCH` followed of a `WHERE` clause, instead of using the `OPTIONAL MATCH`.

**Comment by jrgemignani** [comment]
We are currently working on putting together a list. Joe Fagan is the point person on this.

**Comment by Elektra-K** [comment]
Hello, this would be really useful.  When do you think you will have this published?

**Comment by JoshInnis** [comment]
Our documentation outlines what parts of the openCypher specs is currently supported. https://age.apache.org/docs/master/index.html. Optional Match is curretnly being worked on, we want it out ASAP.

**Comment by JoshInnis** [comment]
OPTIONAL MATCH is now supported. MERGE is expected to be supported by the next release.
