### ISSUE TITLE
How to remove a vertex

### ISSUE THREAD

**Issue by nieyankai** [apache/incubator-age#110]
How to remove a vertex?

**Comment by JoshInnis** [comment]
You should be able to remove a vertex with the DELETE clause. Use MATCH to get the vertices you want to remove. If the vertex has edges attached add the DETACH option before the delete keyword 

`select * from cypher('graph_name', $$ match (n {id: 1}) delete n $$) as (n agtype);`

**Comment by Misterion777** [comment]
Hey @JoshInnis,
tried your query, I'm getting following error:
`ERROR:  return row and column definition list do not match`

**Comment by joefagan** [comment]
That error message was from an earlier release eg 0.4.0 
Please check that the following shows a later version. 
`select extname, extversion from pg_extension where extname='age';`
 extname | extversion
---------+------------
 age     | 0.5.0
(1 row)

The following was run with version 0.5.0 that shows creating and deleting nodes
```

CREATE EXTENSION age;
LOAD 'age';
SET search_path = ag_catalog, "$user", public;

SELECT create_graph('my_graph_name');

SELECT * from cypher('my_graph_name', $$
  CREATE (a:Part {part_num: '123'}), 
         (b:Part {part_num: '345'}), 
         (c:Part {part_num: '456'}), 
         (d:Part {part_num: '789'})
$$) as (a agtype);

-- Delete a node
SELECT * from cypher('my_graph_name', $$
  MATCH (a:Part {part_num: '123'}) DELETE a
$$) as (a agtype);

-- Confirm node deletion
SELECT * from cypher('my_graph_name', $$
  MATCH (a)
  RETURN a
$$) as (a agtype);
```
a
-------------------------------------------------------------------------------------
 {"id": 844424930131970, "label": "Part", "properties": {"part_num": "345"}}::vertex
 {"id": 844424930131971, "label": "Part", "properties": {"part_num": "456"}}::vertex
 {"id": 844424930131972, "label": "Part", "properties": {"part_num": "789"}}::vertex
(3 rows)

**Comment by Misterion777** [comment]
> That error message was from an earlier release eg 0.4.0
> Please check that the following shows a later version.
> `select extname, extversion from pg_extension where extname='age';`
> extname | extversion
> ---------+------------
> age | 0.5.0
> (1 row)
> 
> The following was run with version 0.5.0 that shows creating and deleting nodes
> 
> ```
> 
> CREATE EXTENSION age;
> LOAD 'age';
> SET search_path = ag_catalog, "$user", public;
> 
> SELECT create_graph('my_graph_name');
> 
> SELECT * from cypher('my_graph_name', $$
>   CREATE (a:Part {part_num: '123'}), 
>          (b:Part {part_num: '345'}), 
>          (c:Part {part_num: '456'}), 
>          (d:Part {part_num: '789'})
> $$) as (a agtype);
> 
> -- Delete a node
> SELECT * from cypher('my_graph_name', $$
>   MATCH (a:Part {part_num: '123'}) DELETE a
> $$) as (a agtype);
> 
> -- Confirm node deletion
> SELECT * from cypher('my_graph_name', $$
>   MATCH (a)
>   RETURN a
> $$) as (a agtype);
> ```
> 
> ## a
> {"id": 844424930131970, "label": "Part", "properties": {"part_num": "345"}}::vertex
> {"id": 844424930131971, "label": "Part", "properties": {"part_num": "456"}}::vertex
> {"id": 844424930131972, "label": "Part", "properties": {"part_num": "789"}}::vertex
> (3 rows)

Indeed, i'm on 0.4.0. I'm using official docker container, are there any plans to update it to 0.5.0?

**Comment by joefagan** [comment]
There will be an official incubator-age official docker image soon.
Meanwhile you can do it yourself like this. Takes a few minutes.

I got this from sorrell/docker-agensgraph-extension/dockerfile

Let me know if it works 

create a file called Dockerfile in the some directory with the following contents

```
FROM postgres:11
RUN apt-get update 
RUN apt-get install --assume-yes --no-install-recommends --no-install-suggests \
  bison \
  build-essential \
  ca-certificates \
  flex \
  git \
  postgresql-plpython3-11 \
  postgresql-server-dev-11 

RUN git clone https://github.com/apache/incubator-age /age 

RUN cd /age && make install 

```
Then build the image with
`docker built -t misterion/age .`

then
`docker run -it -e POSTGRES_PASSWORD=mypassword misterion/age`

**Comment by Misterion777** [comment]
> There will be an official incubator-age official docker image soon.
> Meanwhile you can do it yourself like this. Takes a few minutes.
> 
> I got this from sorrell/docker-agensgraph-extension/dockerfile
> 
> Let me know if it works
> 
> create a file called Dockerfile in the some directory with the following contents
> 
> ```
> FROM postgres:11
> RUN apt-get update 
> RUN apt-get install --assume-yes --no-install-recommends --no-install-suggests \
>   bison \
>   build-essential \
>   ca-certificates \
>   flex \
>   git \
>   postgresql-plpython3-11 \
>   postgresql-server-dev-11 
> 
> RUN git clone https://github.com/apache/incubator-age /age 
> 
> RUN cd /age && make install 
> ```
> 
> Then build the image with
> `docker built -t misterion/age .`
> 
> then
> `docker run -it -e POSTGRES_PASSWORD=mypassword misterion/age`

Thanks, will try that

**Comment by joefagan** [comment]
I noticed a typo. Command is docker build (not docker built)

**Comment by joefagan** [comment]
There is a docker image of 0.6.0 now available via
docker pull joefagan/incubator-age

**Comment by joefagan** [comment]
@Misterion777 did it work? Can we close this issue?

**Comment by Misterion777** [comment]
@joefagan yes, it worked, sorry for delay, issue can be closed
