### ISSUE TITLE
Edges are created in the wrong direction

### ISSUE THREAD

**Issue by pdpotter** [apache/incubator-age#119]
When an edge is created following the documentation, the edge is created in opposite direction. Steps to reproduce:

Create two vertices
```
select * from cypher('test_graph', $$CREATE (a:Person {id:1}) return a$$) as (a agtype);
                                      a                                       
------------------------------------------------------------------------------
 {"id": 1125899906842625, "label": "Person", "properties": {"id": 1}}::vertex
(1 row)
```

```
select * from cypher('test_graph', $$CREATE (b:Person {id:2}) return b$$) as (b agtype);
                                      b                                       
------------------------------------------------------------------------------
 {"id": 1125899906842626, "label": "Person", "properties": {"id": 2}}::vertex
(1 row)
```

Create an edge between the vertices. If the edge is returned, it is already clear the edge has the opposite direction.
```
select * from cypher('test_graph', $$MATCH (a:Person {id:1}), (b:Person {id:2}) CREATE (a)-[e:knows]->(b) return e$$) as (e agtype);
                                                              e                                                               
------------------------------------------------------------------------------------------------------------------------------
 {"id": 1407374883553287, "label": "knows", "end_id": 1125899906842625, "start_id": 1125899906842626, "properties": {}}::edge
(1 row)
```

When querying the graph for the edge in the wanted direction, no results are returned.
```
select * from cypher('test_graph', $$MATCH (a:Person {id:1})-[e]->(b:Person {id:2}) return e$$) as (e agtype);
 e 
---
(0 rows)
```

When querying the graph for the edge in the opposite direction, the edge is returned as a result.
```
select * from cypher('test_graph', $$MATCH (a:Person {id:2})-[e]->(b:Person {id:1}) return e$$) as (e agtype);
                                                              e                                                               
------------------------------------------------------------------------------------------------------------------------------
 {"id": 1407374883553287, "label": "knows", "end_id": 1125899906842625, "start_id": 1125899906842626, "properties": {}}::edge
(1 row)
```

**Comment by jrgemignani** [comment]
I am unable to reproduce this in the latest version -

psql-11.5-5432-pgsql=# drop extension age; create extension age; load
'age'; set search_path TO ag_catalog;
ERROR:  extension "age" does not exist
CREATE EXTENSION
LOAD
SET
psql-11.5-5432-pgsql=# SELECT create_graph('test_graph');
NOTICE:  graph "test_graph" has been created
 create_graph
--------------

(1 row)

psql-11.5-5432-pgsql=# select * from cypher('test_graph', $$CREATE
(a:Person {id:1}) return a$$) as (a agtype);
                                      a
-----------------------------------------------------------------------------
 {"id": 844424930131969, "label": "Person", "properties": {"id": 1}}::vertex
(1 row)

psql-11.5-5432-pgsql=# select * from cypher('test_graph', $$CREATE
(b:Person {id:2}) return b$$) as (b agtype);
                                      b
-----------------------------------------------------------------------------
 {"id": 844424930131970, "label": "Person", "properties": {"id": 2}}::vertex
(1 row)

psql-11.5-5432-pgsql=# select * from cypher('test_graph', $$MATCH (a:Person
{id:1}), (b:Person {id:2}) CREATE (a)-[e:knows]->(b) return e$$) as (e
agtype);
                                                             e
----------------------------------------------------------------------------------------------------------------------------
 {"id": 1125899906842625, "label": "knows", "end_id": 844424930131970,
"start_id": 844424930131969, "properties": {}}::edge
(1 row)

psql-11.5-5432-pgsql=# select * from cypher('test_graph', $$MATCH (a:Person
{id:1})-[e]->(b:Person {id:2}) return e$$) as (e agtype);
                                                             e
----------------------------------------------------------------------------------------------------------------------------
 {"id": 1125899906842625, "label": "knows", "end_id": 844424930131970,
"start_id": 844424930131969, "properties": {}}::edge
(1 row)

psql-11.5-5432-pgsql=#

**Comment by yjy44** [comment]
I tried same query, but I couldn't find this issue.

We have to know what version of AGE.

**Comment by Halkrine** [comment]
I tried same query, but I couldn't find this issue.

We have to know what version of AGE.

**Comment by pdpotter** [comment]
Thank you for your quick responses. I am unable to reproduce the issue on a new virtual machine as well.

On my existing virtual machine (Debian buster), the issue occurred with 23ec457c951553994efa7ae9111d7761118a0270, v0.6.0 (3681c90da68353507001db89eb429755d34857f7) and the current master (fa5782f0f03e8172c5f367ad68794756593c18b0).

I managed to fix the issue on my existing virtual machine by uninstalling Apache AGE, uninstalling (purge) postgresql-11 and re-installing everything.
