### ISSUE TITLE
graph visualization tool 

### ISSUE THREAD

**Issue by aysko75** [apache/incubator-age#13]
Is there any graph visualization tool that can be integrated with AGE?

**Comment by grv87** [comment]
@aysko75, [AgensBrowser](https://bitnine.net/downloads-4/agensbrowser-v-1-0/) worked with original AgensGraph version.
I'm not sure on the current status

**Comment by aysko75** [comment]
@grv87, thanks for the reply, ... we (at Bitnine) are working on a new visualization tool that can talk to AGE ... what I am curious to know is whether there is any other individual or company who has built some sort of graph visualization application for AGE ...
