### ISSUE TITLE
ERROR:  extension "age" has no update path from version "0.5.0" to version "0.6.0"

### ISSUE THREAD

**Issue by deem0n** [apache/incubator-age#132]
There are no upgrade scripts, unfortunately. To upgrade I need to drop extension and all dependent data.

```
mi=# select * from pg_available_extensions where name = 'age';
┌──────┬─────────────────┬───────────────────┬────────────────────────┐
│ name │ default_version │ installed_version │        comment         │
├──────┼─────────────────┼───────────────────┼────────────────────────┤
│ age  │ 0.6.0           │ 0.5.0             │ AGE database extension │
└──────┴─────────────────┴───────────────────┴────────────────────────┘
(1 row)

mi=# alter extension age update to '0.6.0';
ERROR:  extension "age" has no update path from version "0.5.0" to version "0.6.0"
mi=# drop extension age;
ERROR:  cannot drop extension age because other objects depend on it
DETAIL:  column id of table age._ag_label_vertex depends on type ag_catalog.graphid
column id of table age._ag_label_edge depends on type ag_catalog.graphid
column start_id of table age._ag_label_edge depends on type ag_catalog.graphid
column end_id of table age._ag_label_edge depends on type ag_catalog.graphid
column properties of table age._ag_label_vertex depends on type ag_catalog.agtype
column properties of table age._ag_label_edge depends on type ag_catalog.agtype
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
mi=# drop extension age cascade;
NOTICE:  drop cascades to 6 other objects
DETAIL:  drop cascades to column id of table age._ag_label_vertex
drop cascades to column id of table age._ag_label_edge
drop cascades to column start_id of table age._ag_label_edge
drop cascades to column end_id of table age._ag_label_edge
drop cascades to column properties of table age._ag_label_vertex
drop cascades to column properties of table age._ag_label_edge
DROP EXTENSION
mi=# create extension age;
CREATE EXTENSION


mi=# select * from pg_available_extensions where name = 'age';
┌──────┬─────────────────┬───────────────────┬────────────────────────┐
│ name │ default_version │ installed_version │        comment         │
├──────┼─────────────────┼───────────────────┼────────────────────────┤
│ age  │ 0.6.0           │ 0.6.0             │ AGE database extension │
└──────┴─────────────────┴───────────────────┴────────────────────────┘
(1 row)
```

**Comment by simonowy** [comment]
This is becoming a big problem as we have to drop (lose) all data to upgrade to the latest version of AGE. Is there a way to avoid this?

**Comment by pdpotter** [comment]
:warning: I haven't tested is.

I don't think the way the data is stored has changed between 0.5 and 0.6 (please correct me if I'm wrong), so you could try:

```
sudo -u postgres pg_dump DATABASE_NAME > backup.sql
sudo -u postgres dropdb DATABASE_NAME
sudo -u postgres createdb -O DATABASE_USER DATABASE_NAME
sudo -u postgres psql DATABASE_NAME < backup.sql
```

**Comment by simonowy** [comment]
I tested what @pdpotter suggested. Lost the graph - that is select * from cypher ('graph_name', ...) ... doesn't work after restore the db.

**Comment by deem0n** [comment]
I had the same experience, but I have found a solution for safe dump/restore and upgrades. Will send Merge Request soon

**Comment by jrgemignani** [comment]
There aren't any real differences on how the data is stored between the recent versions.

We will try to come up with a reasonable way to upgrade from version to version. 

John

**Comment by deem0n** [comment]
> There aren't any real differences on how the data is stored between the recent versions.
> 
> We will try to come up with a reasonable way to upgrade from version to version.
> 
> John

That means, that you can just install new age version (make sure that age.so file is new) and restart PostgreSQL server.

**Comment by deem0n** [comment]
#166 is first step to allow smooth upgrades and dump&restore

**Comment by emotionbug** [comment]
https://github.com/apache/incubator-age/commit/ede73e45acd894d7c17101b6d5af3d76bf18736c
https://github.com/apache/incubator-age/commit/8b438860cd9007db2531a7d449438a03ca75b1bd

These commits allow to upgrade to newer versions.

**Comment by jrgemignani** [comment]
The 1.0.0 release will have scripts for upgrading to the latest version without the need to drop the extension. There will also be scripts for downgrading where possible.
