### ISSUE TITLE
How to install AGE in PostgreSQL 14 on Windows?

### ISSUE THREAD

**Issue by Oleg26Dev** [apache/incubator-age#138]
I did not find any information about the AGE in PostgreSQL 14 on Windows.
How to?

**Comment by pdpotter** [comment]
From https://github.com/apache/incubator-age/issues/127#issuecomment-937982164

> We are still working on finishing up AGE for PG 11, at the moment.
>
> Support for PG 12 and beyond likely won't start until 2022.

**Comment by ShanGor** [comment]
There is a binary ship with PG17, if you want to compile it by yourself, you can ref to it too.
https://github.com/ShanGor/apache-age-windows

Release files: https://github.com/ShanGor/apache-age-windows/releases/tag/PG17%2Fv1.5.0-rc0
