### ISSUE TITLE
difference from AgensGraph

### ISSUE THREAD

**Issue by gorgonzola-oh** [apache/incubator-age#14]
I wonder what AGE is different from AgensGraph

**Comment by jbiz805** [comment]
I'd like to squeeze in relating to this topic. Apart from the fact that one is an extension to PostgreSQL and the other is a full graph database based on PostgreSQL, what's unique about AGE?

**Comment by jrgemignani** [comment]
Correct, the main difference is that AGE is an openCypher plugin (extension) to PostgreSQL whereas AgensGraph is openCypher built into a fork of PostgreSQL.

One item that is unique is that, with a fork, you are tied to a specific version of AgensGraph based off of a specific version of PG. Moving AgensGraph from one version of PG to another isn't trivial. Nor is migrating data into AgensGraph from a PG database.

With an extension you have more flexibility with which versions you can use. Additionally, you can use your existing PG databases as opposed to migrating to AgensGraph.

Currently we are working on getting all of the openCypher functionality into AGE. So, this is all that is unique about AGE relative to AgensGraph.

**Comment by vongosling** [comment]
Do we support distributed deployment in the future? Singe node has very limitation.

**Comment by jrgemignani** [comment]
The goal is to.

Currently, though, we are working on completing the openCypher
implementation.

john

**Comment by JoshInnis** [comment]
To expand upon John's two posts: Cypher can modify data mid-query, in a single node implementation Postgres's transaction system has held up and this has not proven to be an issue. We need to do more research to confirm this won't be an issue in a distributed deployment.

AgensGraph has always been and will always be a single node database that converts the Cypher graph model into a relational model. AGE most notable upcoming goalpost is to emulate that behaviour. We have the ability to make AGE work in a distributed deployment, have sql queries inside a cypher query, use other graph query languages, implement a native graph storage solution within Postgres, etc.  Where AGE ends is up to the community as a whole to decide.
