### ISSUE TITLE
How can i return the graph traversa as JSON using json_build_object? 

### ISSUE THREAD

**Issue by afidegnum** [apache/incubator-age#152]
I needed the following query to be represented as json. 

```
SELECT * from cypher('text_test', $$
          MATCH (V)-[R:connect]-(V2)
          RETURN V,R,V2
$$) as (V agtype, R agtype, V2 agtype);
```
reading from agensgraph documentaiton, I noticed there is a funciton called `json_build_object` but when called, I ended up having an error of `Function ag_catalog.age_json_build_object(agtype) does not exist`
Can you please give an example?

**Comment by pdpotter** [comment]
Agesgraph (https://github.com/bitnine-oss/agensgraph) and Apache AGE (this repository) are two different projects.

`json_build_object` should indeed be supported by Agensgraph, but I can't find anything on this function for Apache AGE.

You could however return the results as a list
```
SELECT * from cypher('text_test', $$
          MATCH (V)-[R:connect]-(V2)
          RETURN [V,R,V2]
$$) as (list agtype);
```
or as a map
```
SELECT * from cypher('text_test', $$
          MATCH (V)-[R:connect]-(V2)
          RETURN {parent: V, relation: R,child: V2}
$$) as (map agtype);
```

**Comment by afidegnum** [comment]
`(map agtype)`, `(list agtype)` are `map` and `list` reserved characters for `agtype`?

**Comment by joefagan** [comment]
@afidegnum 
No map and list are not reserved in SELECT ... as (map agtype)
It returns a map or list only because the RETURN clause is shaped like 
RETURN { , , } --returns map
or
RETURN [ , , ] --returns list

Map and List can be replaced with foo or bar etc. It will rename the column output to foo or bar as shown in this complete example here.


```
-- drop graph for cleanup between tests
SELECT * FROM ag_catalog.drop_graph('test_graph', true);

-- start from a new graph
-- create parent connected to 2 children with multiple properties
SELECT * FROM create_graph('test_graph');
SELECT * FROM cypher('test_graph', $$
    CREATE (p:person {name: 'parent'})
    CREATE (c1:person {name: 'child1', age: 11 })
    CREATE (c2:person {name: 'child2', age: 12 })
    CREATE (p)-[:connect {type: 'is parent'}]->(c1)
    CREATE (p)-[:connect {type: 'is parent'}]->(c2)
    RETURN p
$$) as (p agtype);

SELECT * from cypher('test_graph', $$
          MATCH (p)-[R:connect]->(c)
          RETURN [p.name,R.type,c.name]
$$) as (foo agtype);
```
Last query returns
                foo
-----------------------------------
 ["parent", "is parent", "child2"]
 ["parent", "is parent", "child1"]

**Comment by pdpotter** [comment]
I think this issue has been resolved, I close the issue.

**Comment by jrgemignani** [comment]
I want to add that this function is in PostgreSQL -

`psql-11.5-5432-pgsql=# select proname, prosrc from pg_proc where proname like '%json_build_object%';
      proname      |          prosrc
-------------------+--------------------------
 json_build_object | json_build_object
 json_build_object | json_build_object_noargs
(2 rows)

psql-11.5-5432-pgsql=#
`
This means that it can be called as a "user defined" function. However, that means, it needs to be prefixed with the appropriate schema - pg_catalog and the inputs and outputs need to be cast appropriately. 

An example of a "user defined"  - 

`SELECT * from cypher('expr', $$ RETURN pg_catalog.sqrt(25::pg_float8) $$) as (result agtype);`
