### ISSUE TITLE
ag_graph.c : void value not ignored as it ought to be

### ISSUE THREAD

**Issue by seo-kw** [apache/incubator-age#154]
**Describe the bug**
- I just have installed postgresql 12.9 newly and, continuously, installing age 0.5.0, got error `error: void value not ignored as it ought to be`

**How are you accessing AGE (Command line, driver, etc.)?**
- command line

**What data setup do we need to do?**
- Not about data.

**What is the necessary configuration info needed?**
- sudo apt-get install build-essential libreadline-dev zlib1g-dev flex bison
- sudo apt-get install libreadline-dev gcc make build-essential openssl libssl-dev libedit-dev libpq-dev wget vim 
- wget https://downloads.apache.org/incubator/age/0.5.0.rc0/apache-age-0.5.0-incubating-src.tar.gz
- (_ommiting pg12.9 installing_)
- PATH=/usr/local/pgsql/bin:$PATH
- export PATH
- LD_LIBRARY_PATH=/usr/local/pgsql/lib
- export LD_LIBRARY_PATH
- 

**What is the command that caused the error?**
```pgsql
make PG_CONFIG=/usr/local/pgsql/bin/pg_config install
```

```
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -fPIC -I.//src/include -I. -I./ -I/usr/local/pgsql/include/server -I/usr/local/pgsql/include/internal  -D_GNU_SOURCE   -c -o src/backend/catalog/ag_graph.o src/backend/catalog/ag_graph.c
src/backend/catalog/ag_graph.c: In function 'insert_graph':
src/backend/catalog/ag_graph.c:67:15: error: void value not ignored as it ought to be
   67 |     graph_oid = CatalogTupleInsert(ag_graph, tuple);
      |               ^
make: *** [<builtin>: src/backend/catalog/ag_graph.o] Error 1
```

**Expected behavior**
Complete the installation of age 0.5.0. 

**Environment (please complete the following information):**
- Version:  age 0.5.0
- os : ubuntu:20.04 - linux; amd64 
- docker image : sha256:ba6acccedd2923aee4c2acc6a23780b14ed4b8a5fa4e14e252a23b846df9b6c1

**Additional context**
- Well, is this bug? or am i something wrong? I'm not sure about that..
- anyway, thanks for reading.

**Comment by emotionbug** [comment]
PG 12 is not supported. duplicated with #127

**Comment by seo-kw** [comment]
> 

Oh.. Sorry!!

I didn't come up with searching other's report before i write this. 

anyway, thanks for the reply.
