### ISSUE TITLE
nodejs-pg-age driver returns 'undefined' for primitive column types (v0.7.0)

### ISSUE THREAD

**Issue by bravius** [apache/incubator-age#176]
## Summary

The nodejs driver (node-pg-age) returns _undefined_ for any agtype column that contains a primitive type. 

## Problem description

According to the documentation on Apache AGE types (https://age.apache.org/docs/master/intro/types.html):

> AGE uses a custom data type called agtype, which is the only data type returned by AGE

By this I assume all values returned from AGE are typed as _agtype_. 

I've implemented the nodejs driver, per the instructions on the README page (https://github.com/apache/incubator-age/tree/master/drivers/nodejs/README.md):

The driver works fine, as long as the query returns an agtype that contains an object or an array, but for all primitive types the driver returns _undefined_.

For example, this query:

`SELECT * FROM cypher('dev', $$ RETURN 555 as value $$) as (value agtype)`

the result for value is _undefined_, but 555 was expected.

```
Result {
  command: 'SELECT',
  rowCount: 1,
  oid: null,
  rows: [ { value: undefined } ],
  fields: [
    Field {
      name: 'value',
      tableID: 0,
      columnID: 0,
      dataTypeID: 16448,
      dataTypeSize: -1,
      dataTypeModifier: -1,
      format: 'text'
    }
  ],
  ...
``` 

But, if I define the column type as integer it returns the expected value:

`SELECT * FROM cypher('dev', $$ RETURN 555 as value $$) as (value integer)`
    
```
Result {
  command: 'SELECT',
  rowCount: 1,
  oid: null,
  rows: [ { value: 555 } ],
  fields: [
    Field {
      name: 'value',
      tableID: 0,
      columnID: 0,
      dataTypeID: 16448,
      dataTypeSize: -1,
      dataTypeModifier: -1,
      format: 'text'
    }
  ],
  ...
``` 

My question is, shouldn't the nodejs driver (node-pg-age) parse all valid agtype values -- including numbers, strings and booleans -- not just objects and arrays?

**Comment by emotionbug** [comment]
It will fix it.

https://github.com/apache/incubator-age/pull/177

**Comment by bravius** [comment]
@emotionbug - Thanks very much for the speedy fix, works as expected now.

**Comment by aked21** [comment]
Thanks @emotionbug
