### ISSUE TITLE
Match with order by can not return the node 

### ISSUE THREAD

**Issue by kevintruong** [apache/incubator-age#189]
**Describe the bug**

**How are you accessing AGE (Command line, driver, etc.)?**
- [e.g. JDBC]

**What data setup do we need to do?**
```pgsql
SELECT * from cypher('agegraph', $$ MATCH (n) RETURN n $$) as (n agtype);
+-----------------------------------------------------------------------+
| n                                                                    |
|-----------------------------------------------------------------------|
| {"id": 281474976710662, "label": "", "properties": {"id": 1}}::vertex |
| {"id": 281474976710663, "label": "", "properties": {"id": 2}}::vertex |
| {"id": 281474976710664, "label": "", "properties": {"id": 3}}::vertex |
+-----------------------------------------------------------------------+

...
```

**What is the necessary configuration info needed?**
- [e.g. Installed PostGIS]

**What is the command that caused the error?**
```pgsql
memflask_dev> SELECT * from cypher('agegraph', $$ MATCH (n) ORDER BY n.id RETURN n $$) as (n agtype);


```
```
syntax error at or near "ORDER"
LINE 1: SELECT * from cypher('agegraph', $$ MATCH (n) ORDER BY n.id ...```

**Expected behavior**
A clear and concise description of what you expected to happen.

**Environment (please complete the following information):**
- Version: [e.g. 0.7.0]

**Additional context**
Add any other context about the problem here.

**Comment by jberzy** [comment]
I believe `order by` is just a sub-clause of a projection clause i.e. `return` or `with`. Try placing `order by` clause after the `return` clause.

**Comment by kevintruong** [comment]
```
SELECT * from cypher('agegraph', $$ MATCH (n) RETURN n ORDER BY n.id $$) as (n agtype);
``` 
Tried, but still not work . Thanks for your rsp

**Comment by kevintruong** [comment]
Ok. got it  
```
Note that you cannot sort on nodes or relationships, just on properties on these. ORDER BY relies on comparisons to sort the output, see Ordering and comparison of values.
```

**Comment by jrgemignani** [comment]
The later does work -

> ```
> SELECT * from cypher('agegraph', $$ MATCH (n) RETURN n ORDER BY n.id $$) as (n agtype);
> ```
> 
> Tried, but still not work . Thanks for your rsp

```
psql-11.5-5432-pgsql=# SELECT * from cypher('cypher_vle', $$ MATCH (n) RETURN n ORDER BY n.id $$) as (n agtype);
                                   n
-----------------------------------------------------------------------
 {"id": 844424930131969, "label": "begin", "properties": {}}::vertex
 {"id": 1407374883553281, "label": "middle", "properties": {}}::vertex
 {"id": 1407374883553282, "label": "middle", "properties": {}}::vertex
 {"id": 1407374883553283, "label": "middle", "properties": {}}::vertex
 {"id": 1688849860263937, "label": "end", "properties": {}}::vertex
(5 rows)

psql-11.5-5432-pgsql=# SELECT * from cypher('cypher_vle', $$ MATCH (n) RETURN n ORDER BY id(n) $$) as (n agtype);
                                   n
-----------------------------------------------------------------------
 {"id": 844424930131969, "label": "begin", "properties": {}}::vertex
 {"id": 1407374883553281, "label": "middle", "properties": {}}::vertex
 {"id": 1407374883553282, "label": "middle", "properties": {}}::vertex
 {"id": 1407374883553283, "label": "middle", "properties": {}}::vertex
 {"id": 1688849860263937, "label": "end", "properties": {}}::vertex
(5 rows)

psql-11.5-5432-pgsql=#
```

**Comment by jrgemignani** [comment]
> ```
> SELECT * from cypher('agegraph', $$ MATCH (n) RETURN n ORDER BY n.id $$) as (n agtype);
> ```
> 
> Tried, but still not work . Thanks for your rsp

This does work. What version of AGE are you using?

`psql-11.5-5432-pgsql=# SELECT * from cypher('cypher_vle', $$ MATCH (u) return u $$) as (result agtype);
                                               result
----------------------------------------------------------------------------------------------------
 {"id": 844424930131972, "label": "begin", "properties": {"id": 100, "name": "vertex 100"}}::vertex
 {"id": 1407374883553290, "label": "middle", "properties": {"id": 2, "name": "vertex 2"}}::vertex
 {"id": 1407374883553291, "label": "middle", "properties": {"id": 3, "name": "vertex 3"}}::vertex
 {"id": 1407374883553292, "label": "middle", "properties": {}}::vertex
 {"id": 1688849860263940, "label": "end", "properties": {}}::vertex
(5 rows)

psql-11.5-5432-pgsql=# SELECT * from cypher('cypher_vle', $$ MATCH (u) RETURN u ORDER BY u.id $$) as (result agtype);
                                               result
----------------------------------------------------------------------------------------------------
 {"id": 1407374883553290, "label": "middle", "properties": {"id": 2, "name": "vertex 2"}}::vertex
 {"id": 1407374883553291, "label": "middle", "properties": {"id": 3, "name": "vertex 3"}}::vertex
 {"id": 844424930131972, "label": "begin", "properties": {"id": 100, "name": "vertex 100"}}::vertex
 {"id": 1407374883553292, "label": "middle", "properties": {}}::vertex
 {"id": 1688849860263940, "label": "end", "properties": {}}::vertex
(5 rows)

psql-11.5-5432-pgsql=# SELECT * from cypher('cypher_vle', $$ MATCH (u) RETURN u ORDER BY u.id DESC $$) as (result agtype);
                                               result
----------------------------------------------------------------------------------------------------
 {"id": 1407374883553292, "label": "middle", "properties": {}}::vertex
 {"id": 1688849860263940, "label": "end", "properties": {}}::vertex
 {"id": 844424930131972, "label": "begin", "properties": {"id": 100, "name": "vertex 100"}}::vertex
 {"id": 1407374883553291, "label": "middle", "properties": {"id": 3, "name": "vertex 3"}}::vertex
 {"id": 1407374883553290, "label": "middle", "properties": {"id": 2, "name": "vertex 2"}}::vertex
(5 rows)

psql-11.5-5432-pgsql=# SELECT * from cypher('cypher_vle', $$ MATCH (u) RETURN u ORDER BY u.name $$) as (result agtype);
                                               result
----------------------------------------------------------------------------------------------------
 {"id": 844424930131972, "label": "begin", "properties": {"id": 100, "name": "vertex 100"}}::vertex
 {"id": 1407374883553290, "label": "middle", "properties": {"id": 2, "name": "vertex 2"}}::vertex
 {"id": 1407374883553291, "label": "middle", "properties": {"id": 3, "name": "vertex 3"}}::vertex
 {"id": 1407374883553292, "label": "middle", "properties": {}}::vertex
 {"id": 1688849860263940, "label": "end", "properties": {}}::vertex
(5 rows)

psql-11.5-5432-pgsql=# SELECT * from cypher('cypher_vle', $$ MATCH (u) RETURN u ORDER BY u.name DESC $$) as (result agtype);
                                               result
----------------------------------------------------------------------------------------------------
 {"id": 1407374883553292, "label": "middle", "properties": {}}::vertex
 {"id": 1688849860263940, "label": "end", "properties": {}}::vertex
 {"id": 1407374883553291, "label": "middle", "properties": {"id": 3, "name": "vertex 3"}}::vertex
 {"id": 1407374883553290, "label": "middle", "properties": {"id": 2, "name": "vertex 2"}}::vertex
 {"id": 844424930131972, "label": "begin", "properties": {"id": 100, "name": "vertex 100"}}::vertex
(5 rows)

psql-11.5-5432-pgsql=#
`
