### ISSUE TITLE
How to create a unique constraint on a property, like in AgensGraph?

### ISSUE THREAD

**Issue by bravius** [apache/incubator-age#200]
### Discussed in https://github.com/apache/incubator-age/discussions/199

<div type='discussions-op-text'>

<sup>Originally posted by **bravius** March 15, 2022</sup>
In AgensGraph I could create a unique property constraint using this syntax:

`CREATE CONSTRAINT ON account ASSERT email IS UNIQUE;`

What is the equivalent in Apache AGE for creating a unique constraint on a property?</div>

**Comment by pdpotter** [comment]
There is already an issue about unique properties / indexing at #45. Unique constraints can be added. There is however an issue with unique constraints after the usage of a `set` clause, see #161.

**Comment by bravius** [comment]
@pdpotter - I just had a look at the documentation:

> "Cypher uses a Postgres namespace for every individual graph. It is recommended that no DML or DDL commands are executed in the namespace that is reserved for the graph."

https://age.apache.org/docs/master/intro/graphs.html

This is what I'm confused about. If it's not recommended to use DML or DDL on a graph namespace, does that mean creating indexes like this is a no-no? 

For example:

`CREATE UNIQUE INDEX email ON account((tojsonb(properties)->'email'));`

I just don't understand what the plan is for creating custom constraints and indexes.

Given that the road map has announced a v1.0.0 release candidate for this month, solving the indexing and constraints issues seems fundamental.

**Comment by JoshInnis** [comment]
Creating Unique constraints via pgsql syntax should now be supported.

**Comment by bravius** [comment]
Thanks, works great!

**Comment by JourneyToSilius** [comment]
Hi, I have found this by searching. Does this mean I can set a constraint on a vertex / node with pgsql syntax ? In @bravius example, I guess account is a node or vertex ?
