### ISSUE TITLE
Parsing results?

### ISSUE THREAD

**Issue by akloster** [apache/incubator-age#202]
I'm experimenting with SQL/cypher queries from Python and I've got a problem understanding the return types. First of all, the agensgraph-python extension to psycopg2 doesn't seem to work anymore, unfortunately. So I tried to get around the parsing problem by making more explicit SQL queries like this:

```
cursor.execute("SELECT name from cypher('master_data', $$ MATCH (a) RETURN a.name $$) as (name agtype);")
data = cursor.fetchall()
```
But the return is like  `[('"hello"')]`, so the `name` inside the sql statement is already quoted, right? Is there something I'm not understanding?

**Comment by pdpotter** [comment]
The agtype type is based on jsonb. Returned results are JSON-like.

The ANTLR parser file (https://github.com/apache/incubator-age/blob/master/drivers/Agtype.g4#L64) indicates  that string values should indeed be double quoted.

**Comment by emotionbug** [comment]
When you need parser for agtype on python, reference here.
https://github.com/apache/incubator-age/tree/master/drivers/python

But, case like your query can be alternate from agtype to text.

**Comment by akloster** [comment]
Thank you, that wasn't immediately obvious to me. Also I recommend renaming the driver module from `age` to something like `apache_age` or `psycopg2_age`. 

If using cypher as a subquery to return a string property inside SQL, how would you recommend to "unquote" the string?

**Comment by emotionbug** [comment]
there is a casting for the basic type. so, it can be used as follows.

```
postgres=# SELECT create_graph('test');
SELECT * FROM cypher('test', $$
MATCH (n) RETURN n.name
$$) as (i text);
postgres=# SELECT * FROM cypher('test', $$
CREATE (a {name: 'Alex'} )
$$) as (i agtype);
 i
---
(0 rows)
postgres=# SELECT * FROM cypher('test', $$
MATCH (n) RETURN n.name
$$) as (i text);
  i
------
 Alex
(1 row)
postgres=# SELECT cypher.i, pg_typeof(cypher.i) FROM (SELECT * FROM cypher('test', $$
postgres$# MATCH (n) RETURN n.name
postgres$# $$) as (i text)) cypher;
  i   | pg_typeof
------+-----------
 Alex | text
(1 row)
postgres=# SELECT i::text, pg_typeof(i::text) FROM cypher('test', $$
postgres$# MATCH (n) RETURN n.name
postgres$# $$) as (i text);
  i   | pg_typeof
------+-----------
 Alex | text
(1 row)
```

**Comment by akloster** [comment]
Thank you, this is very helpful!
