### ISSUE TITLE
Dockerfile builds head of master, making Docker Hub builds incongruent with version tag

### ISSUE THREAD

**Issue by sorrell** [apache/incubator-age#204]
**Describe the bug**
The Dockerfile currently clones and builds the head of master. It should either interpret a DOCKER_TAG environment variable or build the files located in the same directory of the checkout (i.e., we're checking out a hash on Docker Hub, and the Dockerfile is located in the root with the source, so we could build in ./ instead of cloning.)

**Comment by JoshInnis** [comment]
@sorrell Has this issue been completely resolved?

**Comment by sorrell** [comment]
@JoshInnis - from a code perspective, yes it is resolved for releases *after* 1.0.0. Until then we need to manually build the 0.7.0 and 1.0.0 release and push to Docker Hub. We can either make that part of this issue or create a separate one if you want.

**Comment by JoshInnis** [comment]
@sorrell I think we should make backwards compatibility for the new docker image. Either way we should replace the docker image urls in the README to the new docker image

**Comment by emotionbug** [comment]
just now, manually pushed v1.0.0, v0.6.0.
Now, just need to modify the README.

**Comment by emotionbug** [comment]
I think this issue has been resolved, I close the issue.
