### ISSUE TITLE
Importing data from CSV

### ISSUE THREAD

**Issue by lnoir** [apache/incubator-age#208]
I'm trying to import an existing graph. The documentation [here](https://age.apache.org/docs/master/intro/agload.html) states that the function `load_labels_from_file` can be used to create vertices from CSV files containing relevant data. However, when I run:
```
SELECT create_vlabel('testgraph','Country');
SELECT load_labels_from_file('testgraph', 'Country', 'age_load/data/countries.csv');
```

I receive the following error:
```
function load_labels_from_file(unknown, unknown, unknown) does not exist
```
The same applies for `load_edges_from_file`. What am I doing wrong? If the above should work, is the function not available in the version I'm using? I'm currently using the [sorrell/apache-age](https://hub.docker.com/r/sorrell/apache-age) docker image.

**Comment by JoshInnis** [comment]
Hi @lnoir,

Are executing `LOAD 'age';` and `SET search_path = ag_catalog, "$user", public;` before calling load_labels_from_file?

**Comment by lnoir** [comment]
Hi @JoshInnis , yes, both of those are run prior to attempting to run `load_[x]_from_file`. I don't receive any errors when using `create_vlabel` or `create_elabel`. I'm also able to run cypher queries without issue. It just seems to be the loading functions that are a problem.

**Comment by emotionbug** [comment]
I think that function was added on v1.0

**Comment by JoshInnis** [comment]
@emotionbug is correct, that function was added in a release that is newer than that docker image, please use this docker image instead https://hub.docker.com/r/apache/age

**Comment by lnoir** [comment]
@emotionbug @JoshInnis Thank you. I've pulled the image and the functions work.

The [README](https://github.com/apache/incubator-age/blob/master/README.md) needs to be updated as it still references the [sorrell/agensgraph-extension](https://hub.docker.com/r/sorrell/agensgraph-extension) which in turn only references [sorrell/apache-age](https://hub.docker.com/r/sorrell/apache-age). It wasn't clear that [apache/age](https://hub.docker.com/r/apache/age) existed.
