### ISSUE TITLE
Query resulting in error: cannot cast agtype integer to type boolean

### ISSUE THREAD

**Issue by lnoir** [apache/incubator-age#211]
Hello again (this might happen a lot).

I'm getting the following error when trying to run the below query: `cannot cast agtype integer to type boolean` (in NodeJS, using pg library):

```
    SELECT * FROM ag_catalog.cypher('minmail', $$      
    MATCH (u:User {_id: $userId})-[:has]->(p:Profile)
    WHERE p.deleted IS NULL
    RETURN p
    $$, $1) as (p ag_catalog.agtype);
```
Params:
```
 '{"userId":"e4510317-67dc-4002-b28d-347699c8f8ca"}' 

```
Any clue as to what I might be doing wrong?

**Comment by pdpotter** [comment]
Is it possible to post the CREATE queries for `u:User` and `p:Profile`?

**Comment by lnoir** [comment]
Hi @pdpotter, they were created via `load_labels_from_file`.

Create statement:
```
SET search_path = ag_catalog, "$user", public;
SELECT create_vlabel('minmail','User');
SELECT create_vlabel('minmail','Profile');
SELECT create_elabel('minmail','has');
SELECT load_labels_from_file('minmail', 'User', '/tmp/export/vertices/User.csv');
SELECT load_labels_from_file('minmail', 'Profile', '/tmp/export/vertices/Profile.csv');
SELECT load_edges_from_file('minmail', 'has', '/tmp/export/edges/has.csv');
```
User data from CSV file:
```
126,"e4510317-67dc-4002-b28d-347699c8f8ca"
```

Profile data from CSV file:
```
128,"011b5316-4390-44ba-9771-c2ff5921b71c","user3","locked","Protected address","TRUE","2022-03-31T18:17:42.000Z","","User Three","email",""
```

**Comment by pdpotter** [comment]
I tried creating a minimal example using for user:
```
SELECT * FROM cypher('minmail', $$
CREATE (u:User {_id: "e4510317-67dc-4002-b28d-347699c8f8ca"})
RETURN u
$$) as (u agtype);
```

for profile I tried:
```
SELECT * FROM cypher('minmail', $$
CREATE (p:Profile {_id: "011b5316-4390-44ba-9771-c2ff5921b71c", deleted: ""})
RETURN p
$$) as (p agtype);
```
```
SELECT * FROM cypher('minmail', $$
CREATE (p:Profile {_id: "011b5316-4390-44ba-9771-c2ff5921b71c", deleted: "TRUE"})
RETURN p
$$) as (p agtype);
```
```
SELECT * FROM cypher('minmail', $$
CREATE (p:Profile {_id: "011b5316-4390-44ba-9771-c2ff5921b71c", deleted: null})
RETURN p
$$) as (p agtype);
```
for the relation:
```
SELECT * FROM ag_catalog.cypher('minmail', $$      
MATCH (u:User {_id: "e4510317-67dc-4002-b28d-347699c8f8ca"}), (p:Profile {_id: "011b5316-4390-44ba-9771-c2ff5921b71c"})
CREATE (u)-[:has]->(p)
$$) as (a ag_catalog.agtype);
```

but I wasn't able to recreate the error message when executing
```
SELECT * FROM ag_catalog.cypher('minmail', $$      
MATCH (u:User {_id: "e4510317-67dc-4002-b28d-347699c8f8ca"})-[:has]->(p:Profile)
WHERE p.deleted IS NULL
RETURN p
$$) as (p ag_catalog.agtype);
```

Is it possible to post the header lines of the CSV files as well?

**Comment by lnoir** [comment]
Thanks @pdpotter. Headers are below.

User.csv:
```
"id","_id"
```

Profile.csv
```
"id","_id","email","access","label","primary","updated","notes","name","match","pattern"
```

**Comment by pdpotter** [comment]
I tried loading the User and Profile from CSV files (except for the :has relation, as I don't have the header and data for that file), but I still don't get an error message. Can you post the header and relevant row of `/tmp/export/edges/has.csv` as well?

Did you check if there are any rows in your CSV files that contain different data?
Have you tried importing CSV files that contain only relevant data rows?

**Comment by lnoir** [comment]
I tried reducing the User.csv to a single user, the Profile.csv to a single Profile, and the has.csv to just that relationship, but still encountering the same issue when running the above query.

has.csv:
```
"start_id","start_vertex_type","end_id","end_vertex_type"
126,"User",128,"Profile"
```

**Comment by pdpotter** [comment]
I imported the `has` relation from csv as well now, and don't encounter errors when executing
```
SELECT * FROM ag_catalog.cypher('minmail', $$      
MATCH (u:User {_id: "e4510317-67dc-4002-b28d-347699c8f8ca"})-[:has]->(p:Profile)
WHERE p.deleted IS NULL
RETURN p
$$) as (p ag_catalog.agtype);
```

Some more toughs:
* Have you tried executing the MATCH query (above) hard coded, so without the parameter?
* What version of Apache Age are you using?

**Comment by lnoir** [comment]
> Have you tried executing the MATCH query (above) hard coded, so without the parameter?

Yes, I was originally running the queries raw, hardcoded directly in pgAdmin4. I ran a few of my existing queries (the data is from an existing graph that uses Cypher) and the results looked sensible. Only then did I start trying to run the queries programmatically in NodeJS.

> What version of Apache Age are you using?

The one tagged [v0.7.0](https://hub.docker.com/layers/age/apache/age/v0.7.0/images/sha256-323c66cd94d1a5a15a924e3a09f33e1b27ac0f5ba49d2a5015befe907298dc67?context=explore) (it was the only one available when I directed to apache/age a couple of days ago.

I'll try with v1.0.0/latest and report the outcome.

**Comment by lnoir** [comment]
I tried v1.0.0, the result was the same. However, latest I get the following error:

```
operator does not exist: ag_catalog.agtype @> ag_catalog.agtype
```
I don't know if it's related to my issue or not.

**Comment by pdpotter** [comment]
There is no upgrade script to upgrade to latest. In order to use the latest version, I think you will have to drop the extension age `DROP EXTENSION age CASCADE` and then create it again `CREATE EXTENSION age` if possible (this will delete all data in your graph database).

**Comment by lnoir** [comment]
Okay, thanks. I followed your instructions and now it's producing the original error. So, no change.

**Comment by JoshInnis** [comment]
Hi @lnoir, 

You said you were using Postgres' NodeJS driver, correct? Not the one located here: https://github.com/apache/incubator-age/tree/master/drivers/nodejs

If you remove the `WHERE p.deleted IS NULL` does that change the error message, what if there is no `{_id: $userId}` That might help us narrow down where the issue is.

**Comment by emotionbug** [comment]
If `search_path` is not specified, the above error may be reproduced.

**Comment by lnoir** [comment]
Okay, I just got to the bottom of this. @emotionbug's comment made me look more carefully at the initial connection and start-up queries. Turns out it was user error. Simplified examples follow.

I was doing something along the lines of:
```
    this.pool = new Pool({ ... });
    this.pool.query(`
        CREATE EXTENSION IF NOT EXISTS age;
        LOAD 'age';
        SET search_path = ag_catalog, "$user", public;
    `);
```
But I realised I needed to perform the setup queries on the client passed to the `connect` event handler:
```
    this.pool.on('connect', async client => {
        await client.query(`
          CREATE EXTENSION IF NOT EXISTS age;
          LOAD 'age';
          SET search_path = ag_catalog, "$user", public;
        `);
    });
```
Now the queries are running without error and returning the expected results.

Thanks @pdpotter @JoshInnis @emotionbug for your help.

**Comment by emotionbug** [comment]
Additionally, in current docker image automatically execute `CREATE EXTENSION`(default database) and `LOAD` statement.
