### ISSUE TITLE
How do I get valid values in a property?

### ISSUE THREAD

**Issue by wqxs** [apache/incubator-age#213]
This is in properties  
`{"userName":"ry"}`

when i go to get it

`SELECT *
FROM ag_catalog.cypher('zjdata_graph', $$
		MATCH (u:sys_user {userId: 1})
		RETURN u.userName
$$) as (userName ag_catalog.agtype);`

The result is
![image](https://user-images.githubusercontent.com/69672009/166883291-2941bdc6-e9d8-4194-a6a7-37b31f341892.png)

and the result I want is ry instead of "ry"

**Comment by pdpotter** [comment]
You'll have to parse the result. Agtype is a superset of Json and a custom implementation of JsonB. For detailed information, see https://age.apache.org/docs/master/intro/types.html (https://age.apache.org/docs/master/intro/types.html#string specificly for strings).

If you query the database from an application written in Go, Java, Javascript (NodeJs) or Python, you can use the corresponding driver from https://github.com/apache/incubator-age/tree/master/drivers to parse the result.

**Comment by JoshInnis** [comment]
You can typecast agtype to text `SELECT * FROM ag_catalog.cypher('zjdata_graph', $$ MATCH (u:sys_user {userId: 1}) RETURN u.userName $$) as (userName text); `

**Comment by JoshInnis** [comment]
You can typecast agtype to text `SELECT * FROM ag_catalog.cypher('zjdata_graph', $$ MATCH (u:sys_user {userId: 1}) RETURN u.userName $$) as (userName text); `
