### ISSUE TITLE
Version 0.3.0 tag

### ISSUE THREAD

**Issue by danieldk** [apache/incubator-age#23]
I have packaged AGE 0.2.0 in [nixpkgs](https://github.com/NixOS/nixpkgs). I would like to update the package to 0.3.0, but there is no git tag for this version (for GitHub projects, we build based on a release tag), only 0.3.0 release candidate 0 seems to be tagged. Would it be possible to create a tag for the commit corresponding to version 0.3.0?

**Comment by JoshInnis** [comment]
There is a release called 'v0.3.0.rc0-incubating' the naming conventions were altered for the first incubating Apache release. Version 0.4.0 resumes the v0.2 release naming conventions.
