### ISSUE TITLE
Parsing failure in extended query protocol

### ISSUE THREAD

**Issue by emotionbug** [apache/incubator-age#28]
Hello.

i trying to use AGE with JDBC.

and, i faced failure when Message Flow is extended query mode with CREATE clause.
has any solution with this issue or guide?

cheers.

**failure query**
```cypher
SELECT * from cypher('my_graph_name', $$
  CREATE (a:Part {part_num: '123'}), 
         (b:Part {part_num: '345'}), 
         (c:Part {part_num: '456'}), 
         (d:Part {part_num: '789'})
$$) as (a agtype);
```

**error message**
```
Type : Error
Length : 98
Severity: ERROR
Code: XX000
Message: unrecognized node type : -1944838080
File : copyfuncs.c
Line: 5658
Routine: copyObjectImpl
```

**environment**
Docker : sorrell/agensgraph-extension-alpine

Cheers.

reference link : https://www.postgresql.org/docs/12/protocol-flow.html#PROTOCOL-FLOW-EXT-QUERY

**Comment by JoshInnis** [comment]
Hello,

Judging from the reference link you attached, I am assuming you are using prepared statements in Postgres' JDBC driver. Is this correct? 

Unfortunately, the CREATE clause is not currently compatible with prepared statements, even if there are no params passed to the Cypher section of the query. We are looking to add this feature in future releases.

**Comment by emotionbug** [comment]
Yes, but it just happened on statement too.
because, Postgres JDBC's default Message Flow is extended mode. 
not in Simple query mode like Node.js or Python.

OK. thank you for replying. :)

**Comment by jrgemignani** [comment]
I will see if I can reproduce the error and see if there might be an
oversight in the copyfuncs.c library.

john

**Comment by jrgemignani** [comment]
Josh is correct. I did not find anything that was an oversight.

john

**Comment by Remi-C** [comment]
Having the same problem folks.
I'm using the Open source DBeaver to run my queries, and I can not create a graph properly.
It works when using psql though.
DBeaver also works when running data querying that does not involves changing the data.
This is a big problem for us, as our users won't use the command line / psql under any circumstances.
--
Workaround : I'm thinking about writing a wrapper in Plpython that runs query inside a bash terminal.
That is pretty ugly though.

**Comment by JoshInnis** [comment]
Hi Remi,

This issue is about creating vertices and edges. Is that the issue you are having or can you not create a graph at all in DBeaver?

**Comment by Remi-C** [comment]
Hey @JoshInnis , thanks for answering :-)
I just followed exactly the query from the doc:
```
SELECT * from cypher('my_graph_name', $$
  CREATE (a:Part {part_num: '123'}), 
        (b:Part {part_num: '345'}), 
        (c:Part {part_num: '456'}), 
        (d:Part {part_num: '789'})
$$) as (a agtype);
```

**Comment by JoshInnis** [comment]
We are working on a fix for this right now. I was able to recreate the issue with DBeaver and will test to verify the fix works there as well.

**Comment by Remi-C** [comment]
Wow you work fast folks ! 
I was very interested by the seminar today, I'm super curious to use this extension with medium to large graphs and see what I can do with it.

**Comment by JoshInnis** [comment]
Hi @emotionbug the JDBC driver is now compatible with Prepared Statements.

@Remi-C, we also tested on DBeaver and the patch should make that compatible to. Btw, glad to hear you enjoyed the presentation.

**Comment by Remi-C** [comment]
Thanks @JoshInnis !
Can I simply pull on master to try it, or do I have to use a specific branch / tag?

**Comment by JoshInnis** [comment]
Currently this patch is only in master.

**Comment by emotionbug** [comment]
I checked. This has been resolved.
