### ISSUE TITLE
Any good tutorials / example schemas / queries for OpenCypher ?

### ISSUE THREAD

**Issue by gorgonzola-oh** [apache/incubator-age#30]
I'd like to see some actual examples. A tutorialish use case if you will. And then, esp here for AGE, to have that example include a mix of Cypher and SQL, using the right subdomain language for each part of an overall interaction with the db.

How are graph edges and nodes exposed to the postgresql type system? Can graph queries / manipulation be done in stored procedures like pl/pgsql? How do relational tables and graphs interact?
---
Original Post in r/postgreSQL
https://www.reddit.com/r/PostgreSQL/comments/lv9u7s/postgresql_with_graph_database_features/gperw36?utm_source=share&utm_medium=web2x&context=3

**Comment by sorrell** [comment]
I agree that more examples/tutorials would be good. I created a quick tutorial here: https://sorrell.github.io/2020/12/10/Postgres-and-Apache-AGE.html
