### ISSUE TITLE
Some homepage update?

### ISSUE THREAD

**Issue by jbiz805** [apache/incubator-age#32]
I noticed roadmap of age.apache.org/# has not updated since... well since it was made. I think updating at least the roadmap can clear some misunderstandings for the new users. (it's March 5th already and AGE is still v0.3.0, not v1.0.0!) 
Also, to let the people know this is an active, ongoing project, I think adding some SNS links related to Apache AGE can be helpful as well. Updating SNS posts are easier and faster than regularly updating a homepage, right?

**Comment by aysko75** [comment]
Pull request for the updates (roadmap) on the website will soon be merged in a day or two.
