### ISSUE TITLE
Impossible to execute AGE functions as non-superuser

### ISSUE THREAD

**Issue by pdpotter** [apache/incubator-age#33]
I installed the Apache AGE PostgreSQL extension on Debian Buster using the instructions on https://age.apache.org/ (under Documentation -> Installing AGE).

I was able to `CREATE EXTENSION age;`, `LOAD 'age';` and `SET search_path = ag_catalog, "$user", public;` as a superuser and subsequently create a graph and execute cypher queries.

Unfortunately, I was unable to execute `LOAD 'age';` as non-superuser.

I tried moving `/usr/lib/postgresql/11/lib/age.so` to `/usr/lib/postgresql/11/lib/plugins/age.so` (as mentioned in https://www.postgresql.org/docs/11/sql-load.html) and was then able to execute `load '$libdir/plugins/age.so';`, but then I got following errors when trying to use AGE functions create_graph and cypher:
```
=> SELECT create_graph('g');
ERROR:  function create_graph(unknown) does not exist
LINE 1: SELECT create_graph('g');
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```
```
=> SELECT * from cypher('g', $$ CREATE (a:Person {name: 'Tom'}) $$) as (a agtype);
ERROR:  function cypher(unknown, unknown) does not exist
LINE 1: SELECT * from cypher('g', $$ CREATE (a:Person {name: 'Tom'})...
                      ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

Is it currently only possible to execute AGE functions as a superuser, or do I need to do additional configuration in order to make them available to non-superusers?

**Comment by jrgemignani** [comment]
Did you execute "set search_path TO ag_catalog;" in the session prior to
executing the "select create_graph('g');" command?

John

**Comment by pdpotter** [comment]
Yes. See below for a more complete listing of the statements I executed after logging in as a non-superuser, who is the owner of the database that is being connected

```
psql -U crdb -W -h 127.0.0.1 -p 5433 crdb
Password: 
psql (11.7 (Debian 11.7-0+deb10u1), server 11.10 (Debian 11.10-0+deb10u1))
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
Type "help" for help.

crdb=> load '$libdir/plugins/age.so'; 
LOAD
crdb=> SET search_path = ag_catalog, "$user", public;
SET
crdb=> SELECT create_graph('g');
ERROR:  function create_graph(unknown) does not exist
LINE 1: SELECT create_graph('g');
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

**Comment by jrgemignani** [comment]
You need to do the following for said user, say *john* for said database,
say *graphdb *-

GRANT USAGE ON SCHEMA *ag_catalog *TO *john*;
GRANT CREATE ON DATABASE *graphdb *TO *john*;

You don't need to do a load, once the extension has been loaded. You just
need to set the search path.

John

**Comment by pdpotter** [comment]
That worked perfectly, thank you so much!
