### ISSUE TITLE
Is there any performance comparison against Neo4J?

### ISSUE THREAD

**Issue by grillorafael** [apache/incubator-age#42]
Hi!

Congratulations on the extension. It looks really nice and I love seeing postgres being used like this.

I wanted to check if anyone here in the project ran a performance comparison against Neo4J to see how it compares.

Thanks!

**Comment by jrgemignani** [comment]
Hi Rafael,

I am not aware of any performance tests, yet. We're mostly focused on fully
implementing the openCypher specification at the moment. Once we have a
fuller implementation, we will be able to start thinking about doing
comparisons.

John

**Comment by grillorafael** [comment]
Thanks!

**Comment by glazkovalex** [comment]
> I wanted to check if anyone here in the project ran a performance comparison against Neo4J to see how it compares.

Not even close to the performance that neo4j has! Here, instead of a graph data model, the usual relational many-to-many is used. A lot of joynes under the hood with a catastrophic drop in performance. Braking Postgresql is braking Postgresql!
