### ISSUE TITLE
unexpected character at or near "$" when using query arguments

### ISSUE THREAD

**Issue by pdpotter** [apache/incubator-age#43]
When I try to use [asyncpg](https://github.com/MagicStack/asyncpg) with query arguments, I get following error: `asyncpg.exceptions.PostgresSyntaxError: unexpected character at or near "$"`

Python reproduction code:
```
import asyncio
import asyncpg


async def main():
    # Don't use prepared statements (see https://github.com/apache/incubator-age/issues/28)
    pool = await asyncpg.create_pool('postgresql://testuser:testpass@127.0.0.1:5433/testdb', statement_cache_size=0)
    async with pool.acquire() as conn:
        await conn.execute(
            '''
                SET search_path = ag_catalog, "$user", public;
            '''
        )

        await conn.execute(
            '''
                SELECT create_graph('testgraph');
            '''
        )

        await conn.execute(
            '''
                SELECT * FROM cypher('testgraph', $$CREATE (v:Person {name: $1})$$) as (a agtype);
            ''',
            'Tom',
        )

asyncio.get_event_loop().run_until_complete(main())
```

When trying to do the same with node with[ node-postgres](https://github.com/brianc/node-postgres), I get a similar error: `error: unexpected character at or near "$"`

Typescript reproduction code:
```
import {Client} from "pg";

const config = {
    user: 'testuser',
    host: '127.0.0.1',
    database: 'testdb',
    password: 'testpass',
    port: 5433,
}

const main = async () => {
    const client = new Client(config);
    await client.connect();

    await client.query(`SET search_path = ag_catalog, "$user", public;`);
    await client.query(`SELECT create_graph('testgraph');`);

    await client.query(
        `SELECT * FROM cypher('testgraph', $$CREATE (v:Person {name: $1})$$) as (a agtype);`,
        [
            'Tom'
        ]
    ).catch(e => console.log(e));
}

main()
```

Is it possible to use query arguments in another way with the [Dollar-Quoted String Constants](https://www.postgresql.org/docs/11/sql-syntax-lexical.html#SQL-SYNTAX-DOLLAR-QUOTING) incubator-age is using, or is there another easy solution to prevent sql injections when using user input?

**Comment by sorrell** [comment]
Some general questions/troubleshooting thoughts:

- Is that error coming from your `SET` command or the `SELECT * from cypher` query?
- Does the code work if you hardcode a name instead of `$1`?
- If not, maybe a library parsing issue? Try spaces after/before the $$ : `$$ CREATE (v:Person {name: $1}) $$ )``

**Comment by pdpotter** [comment]
* The error originates from the `SELECT * from cypher` query.
* In both cases, the hardcoded query `SELECT * FROM cypher('testgraph', $$CREATE (v:Person {name: 'Tom'})$$) as (a agtype);` does work.
* Spaces after/before the $$ don't change the outcome.

Both asyncpg and node-postgres appear to rely on [libpq](https://www.postgresql.org/docs/11/libpq.html).

**Comment by sorrell** [comment]
I am able to reproduce the error, and have a little more detail below regarding where the error occurs in AGE (ag_scanner.l).

```
error: unexpected character at or near "$"
    at Parser.parseErrorMessage (/home/nicho/bitnine/testjs/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/home/nicho/bitnine/testjs/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/nicho/bitnine/testjs/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/nicho/bitnine/testjs/node_modules/pg-protocol/dist/index.js:10:42)
    at Socket.emit (node:events:378:20)
    at addChunk (node:internal/streams/readable:313:12)
    at readableAddChunk (node:internal/streams/readable:288:9)
    at Socket.Readable.push (node:internal/streams/readable:227:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 109,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '75',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'ag_scanner.l',
  line: '711',
  routine: 'ag_scanner_next_token'
```

**Comment by JoshInnis** [comment]
The format `$1` is the Postgres format for parameters and cannot be used in the cypher query. Parameters in the cypher query must take the format `$parameter_name`. When you want to pass parameters to a cypher query, you must add a third argument to the cypher query. This argument must be a Postgres parameter. So your query must look like:

`SELECT * FROM cypher('testgraph', $$CREATE (v:Person {name: $var_name})$$, $1) as (a agtype);`

When executing the query the value passed to `$1` must be an agtype map, where the key is the variable name. NOTE: All 'parameters' in the cypher query are passed in the map.

Also, both AGE parameters and Postgres parameters can only be used in prepared statements. So the above query will not currently work as it is related to the github issues: https://github.com/apache/incubator-age/issues/39 & https://github.com/apache/incubator-age/issues/28. We are currently working on a fix for these issues.

**Comment by JoshInnis** [comment]
@pdpotter The python and NodeJs drivers are now compatible with the CREATE, SET, REMOVE and DELETE clauses. Btw, I never had the opportunity to play around with this particular python driver. Seems like a very interesting library.

**Comment by pdpotter** [comment]
It is now indeed possible to use prepared statements to create nodes. Thank you!
