### ISSUE TITLE
Please document a rust client

### ISSUE THREAD

**Issue by bionicles** [apache/incubator-age#49]
How would a Rust crate access this DB? Can it just submit query strings and be done?

**Comment by JoshInnis** [comment]
Hi,

AGE is an extension of Postgres. So the normal Postgres Crate (https://docs.rs/postgres/0.19.0/postgres/) should be compatible with the extension. Query strings should be in the format outlined here: https://age.apache.org/docs/Apache_AGE_Guide.pdf. Currently there is no custom rust client for AGE.

**Comment by bionicles** [comment]
awesome! how do you like to deploy it?

**Comment by JoshInnis** [comment]
I'm afraid i don't quite understand what you mean by how do we deploy it. Nick Sorrell was kind enough to build some docker images for AGE https://hub.docker.com/r/sorrell/agensgraph-extension. Do you mean how do we deploy AGE or how do we deploy applications written in Rust that use AGE?

**Comment by joefagan** [comment]
@bionicles 
Hi, are you asking how AGE is deployed or how to deploy a Rust application that uses AGE?

**Comment by bionicles** [comment]
haha, I wouldn't expect you guys to figure out my devops problems! but it's interesting to think about how to deploy this. 

an easy way to make this more available would be to add "AMI" to releases, built automatically with packer perhaps, then folks can run AGE on AWS with 1 click without even worrying about docker. ex https://aws.amazon.com/marketplace/pp/Jetware-PostgreSQL-96/B01MRYDTDD 

but we can definitely also make some epic terraform modules for AGE

**Comment by eyab** [comment]
Hello @bionicles, we do have an Apache AGE AMI available. If you would like us to share it with we would need your AWS account number. We will consider adding "AMI" to releases, but we need to review all the licensing before taking any actions.

**Comment by bionicles** [comment]
Cool, just mean to say, any easy ways to get a cloud hosted AGE service running, could definitely help newcomers feel more confident in the project

**Comment by joefagan** [comment]
There is a plan to implement a visualization tool and query editor to access AGE server within the next couple of month.
