### ISSUE TITLE
First cypher execution error after alter database set search_path statement

### ISSUE THREAD

**Issue by kysmou** [apache/incubator-age#57]
In order to connect to the database, the following syntax was executed to execute the cypher syntax by default.

alter database testdb set search_path to ag_catalog, "$user", public;

After that, if you access the database and execute the cypher query, the following error occurs.

1. alter database testdb set search_path to ag_catalog, "$user", public;
2. \q
3. psql testdb -p 5400
4. 
testdb=# SELECT *
testdb-# FROM cypher('graph_name', $$
testdb$# match(a:Person)
testdb$# RETURN a
testdb$# $$) as (a agtype);
ERROR:  unhandled cypher(cstring) function call

5. try again -> normal execute
testdb=# SELECT *
testdb-# FROM cypher('graph_name', $$
testdb$# match(a:Person)
testdb$# RETURN a
testdb$# $$) as (a agtype);
                                                  a                                                  
-----------------------------------------------------------------------------------------------------
 {"id": 844424930131970, "label": "Person", "properties": {"name": "Andres"}}::vertex
 {"id": 844424930131971, "label": "Person", "properties": {"name": "John"}}::vertex
 {"id": 844424930131973, "label": "Person", "properties": {}}::vertex
 {"id": 844424930131974, "label": "Person", "properties": {}}::vertex
 {"id": 844424930131972, "label": "Person", "properties": {"a": "c", "id": 1, "title": "1"}}::vertex
(5 rows)

Is there a problem or am I missing something?

**Comment by pdpotter** [comment]
Did you execute `load 'age';` before the first cypher query (see #41)?

**Comment by kysmou** [comment]
@pdpotter 
Thank you for your teaching. It's solved.
It is inconvenient to execute the load age statement every time cypher is executed.
Is there any method to execute cypher normally in first access without executing "load 'age'";

**Comment by jrgemignani** [comment]
You only need to execute the load once, at the beginning of a session.

**Comment by joefagan** [comment]
@pdpotter to automatically load 'age' see issue #91
