### ISSUE TITLE
Apply bind variable to cypher

### ISSUE THREAD

**Issue by kysmou** [apache/incubator-age#65]
In agensgraph or postgresql, you can increase query reuse (the same query is executed without parsing) 
by applying a bind variable($1) to the where condition value instead of a literal value with a prepare statement.

example)
PREPARE x(text) AS 
SELECT * FROM ( match(a:person) WHERE a.name = $1 return properties(a)) as v;
EXECUTE x(933);

In age, the following error occurs when applying the bind variable ($1).
PREPARE x(text) AS
SELECT *
FROM cypher('graph_name', $$
MATCH (a:Person), (b:Person)
WHERE a.name = $1 AND b.name = 'Node B'
with a,b
match(a)-[e:RELTYPE]->(b)
where b.born > 1999
RETURN a
$$) as (a agtype);
ERROR:  unexpected character at or near "$"
LINE 5: WHERE a.name = $1 AND b.name = 'Node B'

These queries are often implemented in development application environments.
Are there any rules for applying bind variables in age?

**Comment by pdpotter** [comment]
From https://github.com/apache/incubator-age/issues/43#issuecomment-799599013:
> The format `$1` is the Postgres format for parameters and cannot be used in the cypher query. Parameters in the cypher query must take the format `$parameter_name`. When you want to pass parameters to a cypher query, you must add a third argument to the cypher query. This argument must be a Postgres parameter. So your query must look like:
> 
> `SELECT * FROM cypher('testgraph', $$CREATE (v:Person {name: $var_name})$$, $1) as (a agtype);`
> 
> When executing the query the value passed to `$1` must be an agtype map, where the key is the variable name. NOTE: All parameters in the cypher query are passed in the map.

For more information, see the section `Prepared Statements` in the [AGE Guide (PDF)](https://age.apache.org/docs/Apache_AGE_Guide.pdf).

**Comment by kysmou** [comment]
Thank you for your response.
I will check it by referring to the manual again. Thank you so much.

**Comment by kysmou** [comment]
To test the prepared statement, I tested it by referring to the manual.
However, the following error occurs, but if there is something I am doing wrong, please tell me. This is the age 0.4.0 version.

PREPARE cypher_stored_procedure(agtype) AS
SELECT *
FROM cypher('test_graph', $$
MATCH (v:Person)
WHERE v.name = $name 
RETURN v
$$, $1) 
AS (v agtype);

execute cypher_prepared_statement('{"name":"affeee"}');
ERROR:  prepared statement "cypher_prepared_statement" does not exist
STATEMENT:  execute cypher_prepared_statement('{"name":"affeee"}');
prepared statement "cypher_prepared_statement" does not exist

**Comment by JoshInnis** [comment]
In the second example, the prepared statement is called "cypher_stored_procedure" and the execute is for the prepared statement "cypher_prepared_statement."
