### ISSUE TITLE
Formatting create graph error on duplicate

### ISSUE THREAD

**Issue by audiBookning** [apache/incubator-age#66]
This issue is just to bring a minute point.

When using psql to create a graph with
```sql
SELECT create_graph('my_graph_name');
```
the return is
```sh
NOTICE:  graph "my_graph_name" has been created
```
But when the graph is a duplicate the error given is 
```sh
ERROR:  schema "my_graph_name" already exists
```
I was thinking that this message comes probably from postgresql and is not directly controlled by AGE?
Since we are using a AGE function, maybe we should be getting an error similar to:
```sh
ERROR:  graph "my_graph_name" already exists
```
This would help to emphasize the idea that a graph is much more than a schema and to use the AGE functions instead of, for a stretched example, trying to artificially delete a graph by deleting the schema.

**Comment by JoshInnis** [comment]
A patch was added to master that should alter the error message to "ERROR:  graph "my_graph_name" already exists" It is scheduled to go into the next release to.

**Comment by audiBookning** [comment]
Thanks. I will close this issue.
