### ISSUE TITLE
I just got found Apache_AGE_Guide.pdf browser comparability problem in firefox.

### ISSUE THREAD

**Issue by seo-kw** [apache/incubator-age#75]
Well, It's a kind of silly thing. And not a bug in AGE. But who is a newcomer, like me, maybe helpful information.
Maybe we'll test some queries in the official pdf guide through opened browser, but some troubles in a specific browser which is firefox.

If you just copy & paste below query throughout browser, like this query, maybe you've got some error like this
Query : ```SELECT​ *FROM​ cypher(​'graph_name'​, $$​CREATE​ (n), (m)$$) ​as​ (v agtype);```

1. ERROR:  syntax error at or near "SELECT​"
2. ERROR:  cache lookup failed for type 0 at character 28

I got some errors like these. I found nothing helpful and why these errors i've gotten.

Because you copy the query in pdf on firefox, you just got extended-ASCII code together.

firefox copy-paste
1. query: ```SELECT​ * FROM​ cypher(​'a'​, $$​ CREATE​ (n), (m) $$ ) ​as​ (v agtype);```
2. hex : 53 45 4c 45 43 54 **e2 80 8b** 20 2a 20 46 52 4f 4d **e2 80 8b** 20 63 79 70 68 65 72 28 **e2 80 8b** 27 61 27 **e2 80 8b** 2c 20 24 24 **e2 80 8b** 20 43 52 45 41 54 45 **e2 80 8b** 20 28 6e 29 2c 20 28 6d 29 20 24 24 20 29 20 **e2 80 8b** 61 73 **e2 80 8b** 20 28 76 20 61 67 74 79 70 65 29 3b

other browsers copy-paste
1. query: ```SELECT *
FROM cypher('graph_name', $$
CREATE (n), (m)
$$) as (v agtype);```
2. hex : 53 45 4c 45 43 54 20 2a 0d 0a 46 52 4f 4d 20 63 79 70 68 65 72 28 27 67 72 61 70 68 5f 6e 61 6d 65 27 2c 20 24 24 0d 0a 43 52 45 41 54 45 20 28 6e 29 2c 20 28 6d 29 0d 0a 24 24 29 20 61 73 20 28 76 20 61 67 74 79 70 65 29 3b

The error point is "**e2 80 8b**" hex code which means "ZERO WIDTH SPACE". It's completely transparent. but you can backspace that. You can check what it is in [utf-8 chart](https://www.utf8-chartable.de/unicode-utf8-table.pl?start=8192&number=128)

Maybe adding browser recommendations will avoid what have I done.

I just say, In short, do not copy queries in Apache_AGE_Guide.pdf on firefox!

**Comment by joefagan** [comment]
Thank you for the tip.
There is a plan to change the format of the documentation, which may alleviate the issue.

**Comment by joefagan** [comment]
There's a firefox extension that I think stops that behaviour but I haven't tested it.
https://addons.mozilla.org/en-US/firefox/addon/zerowidth-detection/
