### ISSUE TITLE
In assigning label type which is not same as you want to create, Database is forcibly terminated.

### ISSUE THREAD

**Issue by seo-kw** [apache/incubator-age#79]
### Assigning in edge to vertex label.
```
SELECT * FROM cypher('a', $$
MATCH (b), (c) 
WHERE  id(b) = 4222124650659842 and id(c) = 4222124650659843 
CREATE (b)-[a: already_created_vertex_label_name { name:'abc'}]->(c) 
return id(a)
$$) as (a agtype);
```

### Assigning in vertex to edge label.
```
SELECT * FROM cypher('a', $$
create (a: already_created_edge_label_name { name:'abc'})
return id(a)
$$) as (a agtype);
```

Both of them,  print.
```
        server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```

I think.. some error handling logics or guidance help in using ages much better.

Thanks for reading and have a nice day.

**Comment by joefagan** [comment]
FYI AgensGraph 2.1.2 returns these errors respectively
ERROR:  label "already_created_edge_label_name" is edge label
and 
ERROR:  label "already_created_vertex_label_name" is edge label

**Comment by seo-kw** [comment]
Thanks for the reference info, Joe.

> 
> 
> FYI AgensGraph 2.1.2 returns these errors respectively
> ERROR: label "already_created_edge_label_name" is edge label
> and
> ERROR: label "already_created_vertex_label_name" is edge label

**Comment by seo-kw** [comment]
Thanks for the reference info, Joe.
Oh.. I closed again of mistake. sry, 
Reopened.

**Comment by dehowef** [comment]
I put out a patch that corrects this
