### ISSUE TITLE
Is possible to load extension automatically?

### ISSUE THREAD

**Issue by Halkrine** [apache/incubator-age#91]
Hi nice to meet you AGE.

As a AGE beginner, I have a question, so submitted issue.

When I run pgadmin, I have to load 'age' extension every time(AGE is installed by docker). 

So, is possible way to load age extension automatically? 

I can't found how to do..

**Comment by emotionbug** [comment]
edit `shared_preload_libraries` on  `postgresql.conf` ( e.g., /var/lib/postgresql/data/postgresql.conf )

```
# example
shared_preload_libraries = 'age'        # (change requires restart)
```

**Comment by Halkrine** [comment]
> 
> 
> edit `shared_preload_libraries` on `postgresql.conf` ( e.g., /var/lib/postgresql/data/postgresql.conf )
> 
> ```
> # example
> shared_preload_libraries = 'age'        # (change requires restart)
> ```

Thanks! I'll try it.
