### ISSUE TITLE
Go Driver

### ISSUE THREAD

**Issue by uriaash** [apache/incubator-age#98]
I saw in the presentation https://www.youtube.com/watch?v=32w_iVL8qN4 
that there is a driver for Go... but I couldn't find it. I would really like to try AGE and need a Go driver.

**Comment by emotionbug** [comment]
Go parser not merged yet.
https://github.com/apache/incubator-age/pull/87

can you checkout and test this codes?

**Comment by uriaash** [comment]
I'm testing it, thanks!
